WIP: new-build based script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,100 +1,97 @@
-# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+# This file has been generated by `make_travis_yml_2.hs`
+# see https://github.com/hvr/multi-ghc-travis for more information
 language: c
 sudo: false
 
+git:
+  submodules: false  # whether to recursively clone submodules
+
 cache:
   directories:
-    - $HOME/.cabsnap
     - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
 before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
 
 matrix:
   include:
-    - env: CABALVER=1.16 GHCVER=7.0.4 NOTEST=1
-      compiler: ": #GHC 7.0.4"
-      addons: {apt: {packages: [cabal-install-1.16,ghc-7.0.4,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=1.16 GHCVER=7.2.2 NOTEST=1
-      compiler: ": #GHC 7.2.2"
-      addons: {apt: {packages: [cabal-install-1.16,ghc-7.2.2,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=1.16 GHCVER=7.4.2
-      compiler: ": #GHC 7.4.2"
-      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=1.16 GHCVER=7.6.3
-      compiler: ": #GHC 7.6.3"
-      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=1.18 GHCVER=7.8.4
-      compiler: ": #GHC 7.8.4"
-      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=1.22 GHCVER=7.10.1
-      compiler: ": #GHC 7.10.1"
-      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=head GHCVER=head NOTEST=1
-      compiler: ": #GHC head"
-      addons: {apt: {packages: [cabal-install-head,ghc-head,zlib1g-dev], sources: [hvr-ghc]}}
-    - env: CABALVER=head GHCVER=head
-      compiler: ": #GHC head"
+    - compiler: "ghc-7.0.4"
+      env: TEST=--disable-tests
+      addons: {apt: {packages: [cabal-install-head,ghc-7.0.4,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.2.2"
+      env: TEST=--disable-tests
+      addons: {apt: {packages: [cabal-install-head,ghc-7.2.2,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.4.2"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.4.2,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.6.3"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.6.3,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.8.4"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.8.4,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-7.10.3,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.1"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-8.0.1,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [cabal-install-head,ghc-8.0.2,zlib1g-dev], sources: [hvr-ghc]}}
+    - compiler: "ghc-head"
+    # env: CABALVER=head TEST=--disable-tests BENCH=--disable-benchmarks
       addons: {apt: {packages: [cabal-install-head,ghc-head,zlib1g-dev], sources: [hvr-ghc]}}
 
   allow_failures:
-    - env: CABALVER=head GHCVER=head
+    - compiler: "ghc-head"
 
 before_install:
+ - HC=${CC}
  - unset CC
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - if [ "x$NOTEST" = "x" ]; then export CABFLAGS="--enable-tests"; else export CABFLAGS=""; fi
+ - CABALVER=${CABALVER-head}
+ - export PATH=/opt/ghc/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - PATH2=/opt/ghc/${HC/#ghc-}/bin:$PATH
 
 install:
  - cabal --version
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-   then
-     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-   fi
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update -v
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
- - cabal install --only-dependencies $CABFLAGS --dry -v > installplan.txt
- - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
-
-# check whether current requested install-plan matches cached package-db snapshot
- - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
-   then
-     echo "cabal build-cache HIT";
-     rm -rfv .ghc;
-     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
-     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-   else
-     echo "cabal build-cache MISS";
-     rm -rf $HOME/.cabsnap;
-     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
-     cabal install --only-dependencies $CABFLAGS;
-   fi
- 
-# snapshot package-db on cache miss
- - if [ ! -d $HOME/.cabsnap ];
-   then
-      echo "snapshotting package-db to build-cache";
-      mkdir $HOME/.cabsnap;
-      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
-      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
-   fi
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} --dep -j2
 
 # Here starts the actual work to be performed for the package under test;
 # any command which exits with a non-zero exit code causes the build to fail.
 script:
  - if [ -f configure.ac ]; then autoreconf -i; fi
- - cabal configure $CABFLAGS -v2  # -v2 provides useful information for debugging
- - cabal build   # this builds all libraries and executables (including tests/benchmarks)
- - if [ "x$NOTEST" = "x" ]; then cabal test; fi
- - cabal sdist   # tests that a source-distribution can be generated
+ - SRC_BASENAME=$(PATH=${PATH2} cabal info . | awk '{print $2;exit}')
+ # this builds all libraries and executables (including tests/benchmarks)
+ - cabal new-build -w ${HC} ${TEST} ${BENCH}
 
-# Check that the resulting source distribution can be built & installed.
-# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
-# `cabal install --force-reinstalls dist/*-*.tar.gz`
- - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
-   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
+ # there's no 'cabal new-test' yet, so let's emulate for now
+ - TESTS=( $(awk 'tolower($0) ~ /^test-suite / { print $2 }' *.cabal) )
+ - if [ "$TEST" != "--enable-tests" ]; then TESTS=(); fi
+ - shopt -s globstar;
+   RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+   if dist-newstyle/build/**/$SRC_BASENAME/**/build/$T/$T; then echo "= $T OK =";
+   else echo "= $T FAILED ="; RC=false; fi; done; $RC
+ - cabal sdist # test that a source-distribution can be generated
+
+ # Check that the resulting source distribution can be built w/o and w tests
+ - tar -C dist/ -xf dist/$SRC_BASENAME.tar.gz
+ - "echo 'packages: .' > dist/$SRC_BASENAME/cabal.project"
+ - cd dist/$SRC_BASENAME/
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks
+ - rm -rf ./dist-newstyle
+ - cabal new-build -w ${HC} ${TEST} ${BENCH}
 
 # EOF
